version: '3'

services:
  tm-node0:
    image: tendermint/localnode
    networks:
      localnet:
        ipv4_address: 192.167.10.2
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
  narwhal-prim0:
    image: mysten/narwhal:main
    networks:
      localnet:
        ipv4_address: 192.167.10.6
    expose:
      - 54194
      - 54204
      - 54205
    environment:
      - NODE_TYPE=primary
      - VALIDATOR_ID=0
      - MYSTEN_DB_WRITE_BUFFER_SIZE_MB=10
      - MYSTEN_DB_WAL_SIZE_MB=50
      - LOG_LEVEL=-vvv
      - CONSENSUS_DISABLED=--consensus-disabled
    volumes:
      - ./validators:/validators
      - ./validators/validator-0/logs:/home/logs
  narwhal-prim0-worker0:
    image: mysten/narwhal:main
    networks:
      localnet:
        ipv4_address: 192.167.10.7
    expose:
      - 54207
      - 54208
      - 54209
    environment:
      - NODE_TYPE=worker
      - VALIDATOR_ID=0
      - MYSTEN_DB_WRITE_BUFFER_SIZE_MB=10
      - MYSTEN_DB_WAL_SIZE_MB=50
      - LOG_LEVEL=-vvv
      - WORKER_ID=0
    volumes:
      - ./validators:/validators
      - ./validators/validator-0/logs:/home/logs

  tm-node1:
    image: tendermint/localnode
    networks:
      localnet:
        ipv4_address: 192.167.10.3
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
  narwhal-prim1:
    image: mysten/narwhal:main
    networks:
      localnet:
        ipv4_address: 192.167.10.8
    expose:
      - 54194
      - 54192
      - 54193
    environment:
      - NODE_TYPE=primary
      - VALIDATOR_ID=1
      - MYSTEN_DB_WRITE_BUFFER_SIZE_MB=10
      - MYSTEN_DB_WAL_SIZE_MB=50
      - LOG_LEVEL=-vvv
      - CONSENSUS_DISABLED=--consensus-disabled
    volumes:
      - ./validators:/validators
      - ./validators/validator-1/logs:/home/logs
  narwhal-prim1-worker0:
    image: mysten/narwhal:main
    networks:
      localnet:
        ipv4_address: 192.167.10.9
    expose:
      - 54195
      - 54208
      - 54197
    environment:
      - NODE_TYPE=worker
      - VALIDATOR_ID=1
      - MYSTEN_DB_WRITE_BUFFER_SIZE_MB=10
      - MYSTEN_DB_WAL_SIZE_MB=50
      - LOG_LEVEL=-vvv
      - WORKER_ID=0
    volumes:
      - ./validators:/validators
      - ./validators/validator-1/logs:/home/logs

  tm-node2:
    image: tendermint/localnode
    networks:
      localnet:
        ipv4_address: 192.167.10.4
    ports:
      - "26661-26662:26656-26657"
    environment:
      - ID=2
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
  narwhal-prim2:
    image: mysten/narwhal:main
    networks:
      localnet:
        ipv4_address: 192.167.10.10
    environment:
      - NODE_TYPE=primary
      - VALIDATOR_ID=2
      - MYSTEN_DB_WRITE_BUFFER_SIZE_MB=10
      - MYSTEN_DB_WAL_SIZE_MB=50
      - LOG_LEVEL=-vvv
      - CONSENSUS_DISABLED=--consensus-disabled
    expose:
      - 54194
      - 54198
      - 54199
    volumes:
      - ./validators:/validators
      - ./validators/validator-2/logs:/home/logs
  narwhal-prim2-worker0:
    image: mysten/narwhal:main
    networks:
      localnet:
        ipv4_address: 192.167.10.11
    expose:
      - 54201
      - 54208
      - 54203
    environment:
      - NODE_TYPE=worker
      - VALIDATOR_ID=2
      - MYSTEN_DB_WRITE_BUFFER_SIZE_MB=10
      - MYSTEN_DB_WAL_SIZE_MB=50
      - LOG_LEVEL=-vvv
      - WORKER_ID=0
    volumes:
      - ./validators:/validators
      - ./validators/validator-2/logs:/home/logs

  tm-node3:
    image: tendermint/localnode
    networks:
      localnet:
        ipv4_address: 192.167.10.5
    ports:
      - "26663-26664:26656-26657"
    environment:
      - ID=3
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
  narwhal-prim3:
    image: mysten/narwhal:main
    networks:
      localnet:
        ipv4_address: 192.167.10.12
    environment:
      - NODE_TYPE=primary
      - VALIDATOR_ID=2
      - MYSTEN_DB_WRITE_BUFFER_SIZE_MB=10
      - MYSTEN_DB_WAL_SIZE_MB=50
      - LOG_LEVEL=-vvv
      - CONSENSUS_DISABLED=--consensus-disabled
    expose:
      - 54194
      - 54210
      - 54211
    volumes:
      - ./validators:/validators
      - ./validators/validator-3/logs:/home/logs
  narwhal-prim3-worker0:
    image: mysten/narwhal:main
    networks:
      localnet:
        ipv4_address: 192.167.10.13
    expose:
      - 54213
      - 54208
      - 54215
    environment:
      - NODE_TYPE=worker
      - VALIDATOR_ID=2
      - MYSTEN_DB_WRITE_BUFFER_SIZE_MB=10
      - MYSTEN_DB_WAL_SIZE_MB=50
      - LOG_LEVEL=-vvv
      - WORKER_ID=0
    volumes:
      - ./validators:/validators
      - ./validators/validator-3/logs:/home/logs


networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.0/24
